src/Web/Models/BasketViewModel.cs
using System.Collections.Generic;
using System.Linq;

namespace Web.Models
{
    public class BasketViewModel
    {
        public int Id { get; set; }

        public string BuyerId { get; set; }

        public List<BasketItemViewModel> Items { get; set; }

        public int TotalItemsCount => Items.Sum(x => x.Quantity);

        public decimal TotalPrice => Items.Sum(x => x.TotalPrice);

    }
}

src/Web/Models/CheckoutViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Web.Models
{
    public class CheckoutViewModel
    {
        [Required(ErrorMessage = "* required"), MaxLength(180)]
        public string Street { get; set; }

        [Required(ErrorMessage = "* required"), MaxLength(100)]
        public string City { get; set; }

        [Required(ErrorMessage = "* required"), MaxLength(60)]
        public string State { get; set; }

        [Required(ErrorMessage = "* required"), MaxLength(18)]
        public string ZipCode { get; set; }

        [Required(ErrorMessage = "* required"), MaxLength(90)]
        public string Country { get; set; }

        [Required(ErrorMessage = "* required"), MaxLength(50)]
        public string CCOwner { get; set; }

        [Required(ErrorMessage = "* required"), MaxLength(16)]
        public string CCNumber { get; set; }

        [Required(ErrorMessage = "* required"), MaxLength(5)]
        public string CCExpiration { get; set; }

        [Required(ErrorMessage = "* required"), MaxLength(4)]
        public string CCCvv { get; set; }
    }
}

src/Web/Models/OrderCompleteViewModel.cs
namespace Web.Models
{
    public class OrderCompleteViewModel
    {
        public int OrderId { get; set; }
    }
}

src/Web/Controllers/BasketController.cs
using ApplicationCore.Entities;
using ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using Web.Interfaces;
using Web.Models;

namespace Web.Controllers
{
    public class BasketController : Controller
    {
        private readonly IBasketViewModelService _basketViewModelService;
        private readonly IBasketService _basketService;

        public BasketController(IBasketViewModelService basketViewModelService, IBasketService basketService)
        {
            _basketViewModelService = basketViewModelService;
            _basketService = basketService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _basketViewModelService.GetBasketViewModelAsync());
        }

        [HttpPost]
        public async Task<IActionResult> AddToBasket(int productId, int quantity = 1)
        {
            var basket = await _basketViewModelService.AddToBasketAsync(productId, quantity);
            return Json(new NavBasketViewModel() { TotalItemsCount = basket.TotalItemsCount });
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Update([ModelBinder(Name = "quantities")] Dictionary<int, int> quantities)
        {
            await _basketViewModelService.UpdateBasketAsync(quantities);

            return RedirectToAction(nameof(Index));
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Empty()
        {
            var basket = await _basketViewModelService.GetOrCreateBasketAsync();
            await _basketService.DeleteBasketAsync(basket.Id);

            return RedirectToAction(nameof(Index));
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveItem(int basketItemId)
        {
            var basket = await _basketViewModelService.GetOrCreateBasketAsync();
            await _basketService.DeleteBasketItemAsync(basket.Id, basketItemId);

            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        public async Task<IActionResult> Checkout()
        {
            return View();
        }

        [Authorize, HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Checkout(CheckoutViewModel vm)
        {
            if (ModelState.IsValid)
            {
                // payment recevied..

                var address = new Address(vm.Street, vm.City, vm.State, vm.ZipCode, vm.Country);
                var result = await _basketViewModelService.CompleteCheckoutAsync(address);

                return RedirectToAction("OrderComplete", result);
            }

            return View();
        }

        public async Task<IActionResult> OrderComplete(OrderCompleteViewModel vm)
        {
            return View(vm);
        }
    }
}

src/Web/ViewComponents/CheckoutBasketViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Web.Interfaces;

namespace Web.ViewComponents
{
    public class CheckoutBasketViewComponent : ViewComponent
    {
        private readonly IBasketViewModelService _basketViewModelService;

        public CheckoutBasketViewComponent(IBasketViewModelService basketViewModelService)
        {
            _basketViewModelService = basketViewModelService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(await _basketViewModelService.GetBasketViewModelAsync());
        }
    }
}

src/Web/Views/Basket/Checkout.cshtml
@model CheckoutViewModel
@{
    ViewData["Title"] = "Checkout";
}
<div class="row g-5">
    <div class="col-md-5 col-lg-4 order-md-last">
        <vc:checkout-basket />
    </div>
    <div class="col-md-7 col-lg-8">
        <h4 class="mb-3">Shipping address</h4>
        <form class="needs-validation" method="post">
            <div class="row g-3">

                <div class="col-md-8">
                    <label asp-for="Street" class="form-label">Street</label>
                    <input asp-for="Street" type="text" class="form-control" placeholder="1234 Main St" />
                    <div class="text-danger">
                        <span asp-validation-for="Street"></span>
                    </div>
                </div>

                <div class="col-md-4">
                    <label asp-for="City" class="form-label">City</label>
                    <input asp-for="City" type="text" class="form-control">
                    <div class="text-danger">
                        <span asp-validation-for="City"></span>
                    </div>
                </div>

                <div class="col-md-5">
                    <label asp-for="Country" class="form-label">Country</label>
                    <select asp-for="Country" class="form-select">
                        <option value="">Choose...</option>
                        <option>Turkey</option>
                        <option>United States</option>
                    </select>
                    <div class="text-danger">
                        <span asp-validation-for="Country"></span>
                    </div>
                </div>

                <div class="col-md-4">
                    <label asp-for="State" class="form-label">State</label>
                    <input asp-for="State" type="text" class="form-control" />
                    <div class="text-danger">
                        <span asp-validation-for="State"></span>
                    </div>
                </div>

                <div class="col-md-3">
                    <label asp-for="ZipCode" class="form-label">Zip</label>
                    <input asp-for="ZipCode" type="text" class="form-control" placeholder="" />
                    <div class="text-danger">
                        <span asp-validation-for="ZipCode"></span>
                    </div>
                </div>
            </div>

            <hr class="my-4">

            <h4 class="mb-3">Payment</h4>

            <div class="row gy-3">
                <div class="col-md-6">
                    <label asp-for="CCOwner" class="form-label">Name on card</label>
                    <input asp-for="CCOwner" type="text" class="form-control" placeholder="" />
                    <small class="text-muted">Full name as displayed on card</small>
                    <div class="text-danger">
                        <span asp-validation-for="CCOwner"></span>
                    </div>
                </div>

                <div class="col-md-6">
                    <label asp-for="CCNumber" class="form-label">Credit card number</label>
                    <input asp-for="CCNumber" type="text" class="form-control" placeholder="" />
                    <div class="text-danger">
                        <span asp-validation-for="CCNumber"></span>
                    </div>
                </div>

                <div class="col-md-3">
                    <label asp-for="CCExpiration" class="form-label">Expiration</label>
                    <input asp-for="CCExpiration" type="text" class="form-control" placeholder="" />
                    <div class="text-danger">
                        <span asp-validation-for="CCExpiration"></span>
                    </div>
                </div>

                <div class="col-md-3">
                    <label asp-for="CCCvv" class="form-label">CVV</label>
                    <input asp-for="CCCvv" type="text" class="form-control" placeholder="" />
                    <div class="text-danger">
                        <span asp-validation-for="CCCvv"></span>
                    </div>
                </div>
            </div>

            <hr class="my-4">

            <button class="w-100 btn btn-primary btn-lg" type="submit">Complete Payment</button>
        </form>
    </div>
</div>

src/Web/Views/Basket/Index.cshtml
@model BasketViewModel
@{
    ViewData["Title"] = "My Basket";
}

<!--Section: Block Content-->
<section>

    <!--Grid row-->
    <div class="row">

        <!--Grid column-->
        <div class="col-lg-8">

            <!-- Card -->
            <div class="mb-3">
                <form method="post" asp-controller="Basket" asp-action="Update">
                    <div class="pt-4">

                        <div class="d-flex justify-content-between align-items-baseline">
                            <h5 class="mb-4">Cart (<span>@Model.TotalItemsCount</span> items)</h5>

                            <div>
                                <a id="btnEmptyCart" href="#" class="btn btn-sm btn-danger">Empty Cart</a>
                                <button class="btn btn-sm btn-success ms-2">Update Cart</button>
                            </div>
                        </div>

                        @foreach (var item in Model.Items)
                        {
                            <div class="row mb-4">
                                <div class="col-sm-3 col-lg-2 col-xl-2">
                                    <div class="rounded mb-3 mb-md-0">
                                        <img class="img-fluid w-100" src="~/img/products/@item.PictureUri" alt="Sample">
                                    </div>
                                </div>
                                <div class="col-sm-9 col-lg-10 col-xl-10">
                                    <div>
                                        <div class="d-flex justify-content-between">
                                            <div>
                                                <h5>@item.ProductName</h5>
                                                <p class="mb-3 text-muted text-uppercase small">Unit Price: @item.UnitPrice.ToString("c2")</p>
                                            </div>
                                            <div>
                                                <div class="number-input mb-0">
                                                    <input class="quantity form-control" min="1" name="quantities[@item.ProductId]" value="@item.Quantity" type="number">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="d-flex justify-content-between align-items-center">
                                            <div>
                                                <a data-remove-item="@item.Id" href="#" type="button" class="text-decoration-none small text-uppercase me-3">
                                                    <i class="fas fa-trash-alt me-1"></i> Remove item
                                                </a>
                                                <a href="#" type="button" class="text-decoration-none small text-uppercase">
                                                    <i class="fas fa-heart me-1"></i> Move to wish list
                                                </a>
                                            </div>
                                            <p class="mb-0"><span><strong id="summary">@item.TotalPrice.ToString("c2")</strong></span></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <hr class="mb-4">
                        }
                    </div>
                </form>
            </div>
            <!-- Card -->
        </div>
        <!--Grid column-->
        <!--Grid column-->
        <div class="col-lg-4 pl-lg-5">

            <!-- Card -->
            <div class="mb-3">
                <div class="pt-4">

                    <h5 class="mb-3">Total Price</h5>

                    <ul class="list-group list-group-flush">
                        <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
                            Subtotal
                            <span>@Model.TotalPrice.ToString("c2")</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                            Shipping
                            <span>Free</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                            <div>
                                <strong>The total amount of</strong>
                                <strong>
                                    <p class="mb-0">(including taxes)</p>
                                </strong>
                            </div>
                            <span><strong>@Model.TotalPrice.ToString("c2")</strong></span>
                        </li>
                    </ul>

                    <a class="btn btn-primary d-block" href="/Basket/Checkout">Go To Checkout</a>

                </div>
            </div>
            <!-- Card -->

        </div>
        <!--Grid column-->

    </div>
    <!-- Grid row -->

</section>

<form id="frmEmpty" asp-controller="Basket" asp-action="Empty"></form>

<form id="frmRemoveItem" asp-controller="Basket" asp-action="RemoveItem">
    <input id="basketItemId" type="hidden" name="basketItemId" />
</form>

@section Scripts {
<script>
    $("#btnEmptyCart").click(function(event) {
        event.preventDefault();
        $("#frmEmpty").submit();
    });

    $("[data-remove-item]").click(function(event) {
        event.preventDefault();
        var basketItemId = $(this).data("remove-item");
        $("#basketItemId").val(basketItemId);
        $("#frmRemoveItem").submit();
    });
</script>
}

src/Web/Views/Basket/OrderComplete.cshtml
@model OrderCompleteViewModel
@{
    ViewData["Title"] = "Order Complete";
}

<h1>Thank you for your order!</h1>

<p>Your order number is #@Model.OrderId</p>